### ISSUE TITLE
Its not working 

### ISSUE THREAD

**Issue by JuliusBairaktaris** [ssp5zone/whatsbot#1]
As it says isn’t the title it is not working at all it doesn’t even opens the chat

**Comment by ssp5zone** [comment]
Just checked in **Google Chrome** _Version 73.0.3683.103 (Official Build) (64-bit)_ with **Tamper Monkey** _v4.8_ installed. 

The bot's memory seems to be mixed up _(Well, don't expect Skynet. Yet.)_. But, other than that, everything else works dandy.

Maybe, I have not described the Usage part properly.

1. Open Tampermonkey. _(Click on the extension in Chrome > Dashboard)_
2. Click on create new script (**"+"** icon). _(Or, you can directly Click on the extension in Chrome > Create new Script)_
3. Copy the entire contents of src/whatsapp.js in it _(remove anything existing)_ and save.
4. Repeat the same for src/cleverbot.js.
5. Make sure both of them are enabled in Tampermonkey's dashboard.

_Dashboard Settings_
![Dashboard-Settings](http://oi67.tinypic.com/2rp8rhf.jpg)

_WhatsApp Listener_
![WhatsApp Listener](http://oi63.tinypic.com/vo4ubl.jpg)

_CleverBot Listener_
![CleverBot Listener](http://oi66.tinypic.com/98zudh.jpg)

That's it. Now you can open web.whatsapp and tampermonkey would indicate **"1"** script is enabled for the page. _Also, the console should show a debug message "Watching whatsapp" on this page_. If things dont work, try hitting refresh. **Do not refresh once things are set. This will halt all ongoing chats.**

**NOTE:** If you are using Firefox _(with GreaseMonkey)_, you just need to add the settings mentioned in the _==UserScript==_ part of code, manually. It wont automatically detect. The code remains the same.
